solution making change
tomorrowdevs-projects/programming-basics pull request #139
Opened 2021-11-02 09:57 UTC by jimmyhu997

2021-11-05 20:49 UTC, storrisi requested changes
Actually the requirement is not just a simple conversion from cents to other values, but to explain the way you can change an amount (for example , 5 euro) with the less amount of other values.

2021-11-05 20:50 UTC, storrisi commented on projects/m1/003-making-change/solutions/jimmyhu/making-change.py
> +# def change_coins(coins, m, difference):
where this solution comes from?

2021-11-09 17:24 UTC, jimmyhu997 commented
I'm not sure if i have done right the push for the corrections

2021-11-27 15:49 UTC, storrisi approved these changes
It makes more sense now :)

2021-11-27 15:49 UTC, merged